### ISSUE TITLE
Register user with valid token causing error

### ISSUE THREAD

**Issue by alexlyp** [decred/contractor-mgmt#10]
When using a valid email/token pair and using the following info:

username: aa
password: password
name: Alex
Location: USA
pubkey: tpub....

I receive the error: 
400 Bad Request, malformed username

**Comment by alexlyp** [comment]
A quick Trim of the username seemed to fix the issue, though I'm thinking we can fix this issue in `cmswwwcli`

**Comment by sndurkin** [comment]
Hmm, where did you add the trim logic? I would guess that the above info failed because the username is only 2 characters long, and the min username length is 3.
