### ISSUE TITLE
UI suggestion : larger description box, multiline for description and ability to save draft

### ISSUE THREAD

**Issue by Guang168** [decred/contractor-mgmt#35]
1. larger box for description
2. allow entering multiline for description
3. ability to save draft and submit later - i have this error and not able to submit and need to reenter everything when i refresh / logout.

**Comment by s-ben** [comment]
Hey @Guang168, I think you need to submit issues to the main Politeia repo now. They folded CMS into the Politeia code base a few weeks ago.

**Comment by Guang168** [comment]
you are right. thanks ! will repost there and close this.
