### ISSUE TITLE
Restrict to only 1 invoice per user per month

### ISSUE THREAD

**Issue by sndurkin** [decred/contractor-mgmt#6]
Add a restriction in cmswww to enforce that a user can only submit 1 invoice per month.

**Comment by orthomind** [comment]
What's the reason for this restriction? If someone is doing work under two separate approved politeia proposals, would they submit one invoice for work done under both?

**Comment by behindtext** [comment]
for sake of simplicity, contractors should not be submitting more than a single invoice per month. if they are working on multiple proposals, they will tag their line items on the invoice accordingly, e.g. billing N_A hours for proposal A and N_B hours for proposal B. this is already handled by the current invoice format.
